name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
- type: markdown
  attributes:
    value: "**Please make sure you are on the latest version.**"
- type: textarea
  id: what-happened
  attributes:
    label: Describe the bug
    placeholder: The following error occurs when doing X when I have X enabled. 
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Relevant errors (if available)
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. Open Obsidian's Developer Console by pressing CTRL + SHIFT + I
    render: Shell
- type: textarea
  id: reproduce
  attributes:
    label: Steps to reproduce
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
- type: textarea
  id: context
  attributes:
    label: Additional context
    description: Add any other additional context about the problem here.
- type: dropdown
  id: version
  attributes:
    label: Operating system
    description: Which OS are you using?
    options:
      - Windows
      - Linux
      - macOS
      - iOS
      - Android
  validations:
    required: true
